apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../base
- namespace.yaml
images:
- name: python-webapp-2/webapp:1.0.0
  newName: gcr.io/mavencode-project/python-webapp-demo_2
  newTag: 4fcc2d2e39af02a32c10176a516c2e256f4816a6
- name: python-webapp/webapp:1.0.0
  newName: gcr.io/mavencode-project/python-webapp-demo
  newTag: 4fcc2d2e39af02a32c10176a516c2e256f4816a6
