apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../base
- namespace.yaml
images:
- name: python-webapp/webapp:1.0.0
  newName: gcr.io/mavencode-project/python-webapp-demo
  newTag: a8131ad82db898c70ad2ae956a2e0d95fcb527c6
