apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: mavencode-q1-2020-service
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: mavencode-q1-2020-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mavencode-q1-2020-app
  name: mavencode-q1-2020-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavencode-q1-2020-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mavencode-q1-2020-app
    spec:
      containers:
      - image: mavencode/website:1.0.1
        imagePullPolicy: Always
        name: mavencode-q1-2020-app
        ports:
        - containerPort: 8000
