apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: python-webapp-service
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-webapp-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-webapp-app
  name: python-webapp-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-webapp-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-webapp-app
    spec:
      containers:
      - image: gcr.io/mavencode-project/python-webapp-demo:7d339478715b5913e148cb666d0d21983fc6ba19
        imagePullPolicy: Always
        name: python-webapp-app
        ports:
        - containerPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: social
            port:
              number: 8000
        path: /social
        pathType: ImplementationSpecific
      - backend:
          service:
            name: blog
            port:
              number: 8001
        path: /blog
        pathType: ImplementationSpecific
      - backend:
          service:
            name: training
            port:
              number: 8002
        path: /training
        pathType: ImplementationSpecific
      - backend:
          service:
            name: api
            port:
              number: 8003
        path: /api
        pathType: ImplementationSpecific
